langauage: python
python:
- 3.6

before_install:
- openssl aes-256-cbc -K $encrypted_d1cf0bfee7b7_key -iv $encrypted_d1cf0bfee7b7_iv
  -in secrets.tar.enc -out secrets.tar -d

install:
- pip install -r requirements.txt
before_script:
- cd instagram
script:
- python manage.py test
